import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    drawer: {
      backgroundColor: '#FAFAFA',
      width: 300,
   },
    draweritem: {
     //activeTintColor: "#C62828",
     fontSize: 25,
     //labelStyle: {fontSize:30, fontWeight: 'bold'},
   },
    input: {
      margin: 14,
      height: 60,
      borderRadius: 4,
      justifyContent: "center",
      textAlign: "center",
      fontSize: 20,
      includeFontPadding: false,
      color: "#808080",
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    boton: {
      alignItems: "center",
      alignSelf: "center",
      backgroundColor: "#961515",
      borderRadius: 4,
      padding: 16,
      shadowColor: "#000",
      shadowOpacity: 0.5,
      shadowRadius: 5,
      elevation: 5,
    },
    botonText:{
      justifyContent: "center",
      textAlign: "center",
      fontSize: 18,
      includeFontPadding: false,
      color: "#FFFFFF",
      fontWeight: "bold",
    },
    botonGuardarContactos: {
      display:"flex",
      flexDirection:"row",
      position: 'absolute',  
      bottom: 0,
      zIndex: 100,
      alignItems: "center",
      alignSelf: "center",
      backgroundColor: "#961515",
      borderRadius: 4,
      margin: 14,
      padding: 16,
      shadowColor: "#000",
      shadowOpacity: 0.5,
      shadowRadius: 5,
      elevation: 5,
    },
    IconSynchronize:{
      display: "flex",
      width: "20",
      height: "20",
    },
    contenedorDetallesUserCard:{
      display: "flex",
      justifyContent: "center",
      margin: 10,
    },
    contenedorBotonesUserCard:{
      position: "absolute",
      alignSelf: "center",
      display: "flex",
      flexDirection: "row",
      bottom: 10,
      margin:10,
    },
    botonVerMas:{
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 4,
    },
    textoVerMas:{
      padding: 6,
      justifyContent: "center",
      textAlign: "center",
      fontSize: 12,
      includeFontPadding: false,
      color: "#961515",
      fontWeight: "bold",
    },
    botonImportar:{
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 4,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
      backgroundColor: "#961515",
    },
    textoImportar:{
      justifyContent: "center",
      textAlign: "center",
      fontSize: 12,
      includeFontPadding: false,
      color: "#FFFFFF",
      fontWeight: "bold",
    },
    integrante:{
      fontSize: 25,
      justifyContent: "center",
      textAlign: "center",
      lineHeight: 50,
    },
    p: {
      fontSize: 20,
      lineHeight: 30,
    },
    h1:{
      fontSize: 30,
      margin: 12,
      fontWeight: "bold"
    },
    header:{
      paddingTop:25,
      flexDirection: "row",
      alignItems: 'center',
      backgroundColor: "#B71C1C",
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    h1header:{
      fontSize: 28,
      margin: 12,
      fontWeight: "bold",
      color: "#FFFFFF",
    },
    burgerButton:{
      alignItems: 'center',
      justifyContent: 'center',
      width: 56,
      height: 56,
    },
    IconBurger:{
      height: 45,
      width: 45,
    },
    listViewContainer:{
      margin: 14,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    listViewHeader:{
        paddingHorizontal: 14,
        justifyContent: "center",
        textAlign: "center",
        height: 56,
        backgroundColor: "#B71C1C",
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowRadius: 2.22,
        elevation: 3,
    },
    listContent:{
      justifyContent:'center',
      alignItems:'center',
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    listCard:{
      marginTop:22,
      marginHorizontal: 5,
      height: 250,
      width: 165,
      borderRadius: 4,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    listImage:{
      width: 165,
      height: 80,
      resizeMode : 'cover',
      position: 'relative',
      alignSelf: 'center',
    },
    modalContainer:{
      display: 'flex',
    },
    modal:{
      padding:30,
    },
    modalImage:{
      width: 140 ,
      height: 140,
      borderRadius: 4,
    },
    closeModal:{
      display: "flex",
      alignContent: "flex-end",
      fontSize: 25,
      color: "#B71C1C",
      fontWeight: "bold",
    },
    modalHeader:{
      flexDirection: 'row',
      justifyContent: "space-between" ,
      paddingVertical: 20,
    },
    modalContent:{
      paddingVertical: 20,
    }, 
    commentH1:{
      fontSize: 22,
      fontWeight: "bold",
      includeFontPadding: false, 
      paddingVertical:14,
    },
  });

  export {styles};