import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    drawer: {
      backgroundColor: '#FAFAFA',
      width: 300,
   },
    draweritem: {
     //activeTintColor: "#C62828",
     fontSize: 25,
     //labelStyle: {fontSize:30, fontWeight: 'bold'},
   },
    input: {
      margin: 14,
      lineHeight: 16,
      borderRadius: 4,
      padding: 12,
      flex: 1,
      justifyContent: "center",
      textAlign: "center",
      fontSize: 16,
      includeFontPadding: false,
      color: "#808080",
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    boton: {
      flex:1,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#961515",
      borderRadius: 4,
      marginHorizontal: 14,
      paddingVertical: 16,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    botonText:{
      flex: 1,
      justifyContent: "center",
      textAlign: "center",
      fontSize: 18,
      includeFontPadding: false,
      color: "#FFFFFF",
      fontWeight: "bold",
    },
    botonGuardarContactos: {
      position: 'absolute',  
      bottom: 0,
      zIndex: 100,
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
      backgroundColor: "#961515",
      borderRadius: 4,
      width: "100%",
      margin: 10,
      paddingVertical: 16,
      shadowColor: "#000",
      shadowOpacity: 0.5,
      shadowRadius: 5,
      elevation: 5,
    },
    contenedorDetallesUserCard:{
      display: "flex",
      justifyContent: "center",
      margin: 10,
    },
    contenedorBotonesUserCard:{
      position: "absolute",
      alignSelf: "center",
      display: "flex",
      flexDirection: "row",
      bottom: 10,
      margin:10,
    },
    botonVerMas:{
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 4,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
      marginRight: 5,
    },
    textoVerMas:{
      flex: 1,
      justifyContent: "center",
      textAlign: "center",
      fontSize: 12,
      lineHeight:25,
      includeFontPadding: false,
      color: "#961515",
      fontWeight: "bold",
    },
    botonImportar:{
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 4,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
      backgroundColor: "#961515",
    },
    textoImportar:{
      flex: 1,
      justifyContent: "center",
      textAlign: "center",
      fontSize: 12,
      includeFontPadding: false,
      color: "#FFFFFF",
      fontWeight: "bold",
    },
    integrante:{
      fontSize: 25,
      justifyContent: "center",
      textAlign: "center",
      lineHeight: 50,
    },
    p: {
      fontSize: 16,
      lineHeight: 30,
    },
    h1:{
      fontSize: 30,
      margin: 12,
      fontWeight: "bold"
    },
    header:{
      paddingTop:25,
      flexDirection: "row",
      alignItems: 'center',
      backgroundColor: "#B71C1C",
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    h1header:{
      fontSize: 28,
      margin: 12,
      fontWeight: "bold",
      color: "#FFFFFF",
    },
    burgerButton:{
      alignItems: 'center',
      justifyContent: 'center',
      width: 56,
      height: 56,
    },
    IconBurger:{
      height: 45,
      width: 45,
    },
    listViewContainer:{
      margin: 14,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    listViewHeader:{
        paddingHorizontal: 14,
        flex: 1,
        justifyContent: "center",
        textAlign: "center",
        flexDirection: "row",
        height: 56,
        backgroundColor: "#B71C1C",
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowRadius: 2.22,
        elevation: 3,
    },
    listContent:{
      justifyContent:'center',
      alignItems:'center',
    },
    listCard:{
      marginTop:22,
      marginHorizontal: 5,
      height: 220,
      width: 165,
      borderRadius: 4,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 2.22,
      elevation: 3,
    },
    listImage:{
      width: 165,
      height: 80,
      resizeMode : 'cover',
      position: 'relative',
      alignSelf: 'center',
    },
    modalContainer:{
      backgroundColor: "red",
    },
    modal:{
      backgroundColor: 'blue',
    },
  });

  export {styles};